# Generated by Django 3.2.22 on 2024-01-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20240115_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='gender',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
