# Generated by Django 3.2.22 on 2024-01-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('authname', models.CharField(max_length=30)),
                ('bdesc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
